### PR TITLE
Adds a tilt-to-wake icon.

### PR DESCRIPTION
**Pull request by MagneFire**
This PR provides simple tilt-to-wake icons used by the asteroid-settings PR(https://github.com/AsteroidOS/asteroid-settings/pull/23).

Please let me know what you think of these icons. Suggestions are highly appreciated :)

### CODE REVIEW

**Comment by jrtberlin** [comment]
I like the concept and the overall icon idea. However, I think the watch strap looks a bit unpolished at the bottom.

**Comment by MagneFire** [comment]
Thanks :)
This is just the `ios-watch` and `ios-sync` icons merged and rotated.

I agree with the look of the strap. I can try to reduce the size of the strap all together and increasing the size of the watch. That might help make the icon better looking and less unpolished :)

**Comment by MagneFire** [comment]
ok, I have been messing around a bit, what do you think of these versions:

ios-tilttowake

ios-tilttowake-2

**Comment by jrtberlin** [comment]
I think they look a lot better!

**Comment by MagneFire** [comment]
Great! I will adjust the PR. Which one do you like more, the bottom one?

**Comment by jrtberlin** [comment]
@MagneFire I like the top one better since there is less going on. simpler is better imho

**Comment by MagneFire** [comment]
Alright, I agree with that :)
I have updated the PR.

Thanks for your feedback :smile:

**Comment by FlorentRevest** [comment]
I agree with everything that has been said above :)
They look great like this. Could you just make them go through a svg minifier ?

**Comment by MagneFire** [comment]
Great! :+1: 

I have minified the svgs.

**Comment by FlorentRevest** [comment]
Mh are you sure? I still see comments, inkscape tags and \n

**Comment by MagneFire** [comment]
Snap, I just used an online svg minimizer ;)
Ill look into the inkscape one.

**Comment by MagneFire** [comment]
Alright, how about know?

**Comment by FlorentRevest** [comment]
Mhh, it still looks like it could be made shorter but don't worry about it, that will do ;) 
This is certainly not what will take the most disk space or processing power on the watch anyway ahah.

**Pull request merged**
